### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by clarkd** [401Unauthorized/broadlink-bridge#4] opened 2020-12-04 20:01 UTC
I've reset my RM Mini 3 and confirmed it's now connected to the wifi network.

I've added a blaster via Postman using it's IP and MAC address. But when I try and learn a command it times out?

How can I debug this and see what is going on?

Thanks

**Comment by 401Unauthorized** [comment] 2020-12-04 21:40
Hi @clarkd, sure, thanks for reaching out.

To confirm what you mentioned, you were able to use the CLI to connect the RM Mini 3 to your network (does it have a static IP address?) and then the API to add the blaster to the local database (you can verify all looks correct by [checking the db.json file](https://github.com/401Unauthorized/broadlink-bridge#review-server-files)).

Here are some ides to look into in order to determine where the issue is:
1.  Were you able to [add a "device" ](https://github.com/401Unauthorized/broadlink-bridge#post-blastersblaster-iddevices) using the API as well? 

2. Test if you are actually able to communicate with the blaster. Manually edit the db.json file to add some fake commands under the device. For instance, you can use [these sample commands](https://github.com/401Unauthorized/broadlink-bridge#get-blastersblaster-iddevicesdevice-idcommands). While pointing your phone camera at the blaster, using the API for [Emit IR Endpoints](https://github.com/401Unauthorized/broadlink-bridge#emit-ir-endpoints) in order to emit those commands on the blaster. Do you see the IR lights blinking?

3. I've observed this exact issue before when the "type" of the blaster is incorrect. Take a look at the [documentation](https://github.com/401Unauthorized/broadlink-bridge#post-blasters) and make sure you are setting the correct "type". When following those steps, you may notice there are numerous RM Mini 3 [options](https://github.com/401Unauthorized/broadlinkjs-rm/blob/master/index.js#L8) based on the hardware revision of the blaster. I purchased two "RM Mini 3" devices on Amazon and they were not the same (one was "Broadlink RM Mini 3 D", other was "Broadlink RM Mini 3 E"), it took a while to realize this was the root cause.

Hopefully this gets things working! If it does, let me know. If not, I can look into it further.

**Comment by 401Unauthorized** [comment] 2020-12-19 21:59
@clarkd I am checking back in to see if you are still having this issue? I'll go ahead and close this in 48 hours if I do not hear baclk

**Closed** 2020-12-24 01:35 UTC
Labels: support
